### ISSUE TITLE
NoMethodError: undefined method `text' for nil:NilClass

### ISSUE THREAD

**Issue by kawakubox** [kawakubox/uma#18]
https://sentry.io/kawakuboxcom/uma/issues/290761698/

```
NoMethodError: undefined method `text' for nil:NilClass
  app/models/scraper/race_entry.rb:127:in `ordinal'
    end
  app/models/scraper/race_entry.rb:13:in `scrape!'
    ordinal:        ordinal,
  app/jobs/scrape_race_entry_job.rb:9:in `perform'
    Scraper::RaceEntry.new(race_id).scrape!
  bin/rails:9:in `<top (required)>'
    require 'rails/commands'
...
(72 additional frame(s) were not displayed)

NoMethodError: undefined method `text' for nil:NilClass
```

**Comment by kawakubox** [comment]
https://sentry.io/kawakuboxcom/uma/issues/290761698/

**Comment by kawakubox** [comment]
なぞ、正しく取れるようにも見える

**Comment by kawakubox** [comment]
再実行で正常終了、再現せず。

**Comment by kawakubox** [comment]
HTML取得時に http status 200 で取れていない可能性

**Comment by kawakubox** [comment]
https://sentry.io/kawakuboxcom/uma/issues/292448173/

**Comment by kawakubox** [comment]
https://sentry.io/kawakuboxcom/uma/issues/293534316/

**Comment by kawakubox** [comment]
https://sentry.io/kawakuboxcom/uma/issues/293494924/
